# Generated by Django 3.1.12 on 2025-01-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=6)),
                ('student_class', models.CharField(max_length=50)),
                ('major_Subject', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
